### ISSUE TITLE
[Bug]: OpenTelemetry 오류 발생

### ISSUE THREAD

**Issue by k1g99** [skkuding/codedang#1570]
### Describe the bug

Tracer 생성 과정에서 오류가 발생합니다. 
일단 임시로 #1568 로 버전 낮춰서 해결해놓기는 했지만, 정확한 확인이 필요합니다. 

### Reproduction

1. Trace 생성 시 오류 발생

### Logs

```
this._spanLimits = parentTracer.getSpanLimits();
                                    ^
TypeError: parentTracer.getSpanLimits is not a function
    at new Span (/workspace/node_modules/.pnpm/@opentelemetry+sdk-trace-base@1.22.0_@opentelemetry+api@1.8.0/node_modules/@opentelemetry/sdk-trace-base/src/Span.ts:122:37)
    at /workspace/node_modules/.pnpm/@prisma+instrumentation@5.11.0/node_modules/@prisma/instrumentation/dist/chunk-VVAFFO6L.js:59:20
    at Array.forEach (<anonymous>)
    at ActiveTracingHelper.createEngineSpan (/workspace/node_modules/.pnpm/@prisma+instrumentation@5.11.0/node_modules/@prisma/instrumentation/dist/chunk-VVAFFO6L.js:44:27)
    at eo.createEngineSpan (/workspace/node_modules/.pnpm/@prisma+client@5.11.0_prisma@5.11.0/node_modules/@prisma/client/runtime/library.js:122:1645)
    at xt.logger (/workspace/node_modules/.pnpm/@prisma+client@5.11.0_prisma@5.11.0/node_modules/@prisma/client/runtime/library.js:112:1167)
    at /workspace/node_modules/.pnpm/@prisma+client@5.11.0_prisma@5.11.0/node_modules/@prisma/client/runtime/library.js:112:922
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/skkuding/next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [X] Check that there isn't already an issue

**Comment by k1g99** [comment]
Dependency 문제로, #1566  머지되면 해결될 것 같습니다.
