### ISSUE TITLE
[Bug]: vscode prettier extension doesn't work

### ISSUE THREAD

**Issue by jspark2000** [skkuding/codedang#496]
### Describe the bug

vscode 에디터에서 코드 저장시 prettier extension이 동작하지 않는 문제 발생

해결 방법
.vsode/settings.json 에 아래의 코드 추가
```
"prettier.prettierPath": "./node_modules/prettier"
```

Reference
https://github.com/prettier/prettier-vscode/issues/3019

### Reproduction

```
["ERROR" - 9:27:01 AM] Cannot read properties of undefined (reading 'uid')
TypeError: Cannot read properties of undefined (reading 'uid')
	at Object.statSync (/vscode/vscode-server/bin/linux-arm64/695af097c7bd098fbf017ce3ac85e09bbc5dda06/node_modules/graceful-fs/polyfills.js:313:17)
	at p (/home/node/.vscode-server/extensions/esbenp.prettier-vscode-9.13.0/dist/extension.js:1:35221)
	at L (/home/node/.vscode-server/extensions/esbenp.prettier-vscode-9.13.0/dist/extension.js:1:37052)
...
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/skkuding/next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [X] Check that there isn't already an issue

**Comment by dotoleeoak** [comment]
https://github.com/prettier/prettier-vscode/pull/3030
관련 update가 이뤄진 거 같은데, 기다려보는 건 어떨까요?

**Comment by jspark2000** [comment]
좋습니다!

**Comment by dotoleeoak** [comment]
이슈 해결된 거 확인되면 다시 닫을게요!!
