### ISSUE TITLE
[Bug]: User withdrawal API 에러 

### ISSUE THREAD

**Issue by dotoleeoak** [skkuding/codedang#939]
### Describe the bug

`/api/user/withdrawal`를 호출할 때, 해당 user와 연결된 submission이 있으면 에러가 발생합니다.
Submission model에 `onDelete` action이 지정되지 않은 것이 원인인 것 같습니다.

아래 코드를 보면 `this.deleteUser()` 호출 전 `await` keyword가 빠져있는데, 그래서 응답은 201로 전달되지만 다른 요청이 모두 502로 거부됩니다.

```
  async withdrawal(username: string, withdrawalDto: WithdrawalDto) {
    const user: User = await this.getUserCredential(username)

    if (
      !(await this.jwtAuthService.isValidUser(user, withdrawalDto.password))
    ) {
      throw new UnidentifiedException('password')
    }

    this.deleteUser(username)
  }
```

### Reproduction

1. 개발 서버에서 `user01` 로그인
2. `POST /api/user/withdrawal` 호출
3. 서버 로그 확인

### Logs

```
PrismaClientKnownRequestError: 
Invalid `prisma.user.delete()` invocation:


Foreign key constraint failed on the field: `submission_user_id_fkey (index)`
    at Cn.handleRequestError (/node_modules/.pnpm/@prisma+client@5.4.2_prisma@5.4.2/node_modules/@prisma/client/runtime/library.js:123:6817)
    at Cn.handleAndLogRequestError (/node_modules/.pnpm/@prisma+client@5.4.2_prisma@5.4.2/node_modules/@prisma/client/runtime/library.js:123:6206)
    at Cn.request (/node_modules/.pnpm/@prisma+client@5.4.2_prisma@5.4.2/node_modules/@prisma/client/runtime/library.js:123:5926)
    at async l (/node_modules/.pnpm/@prisma+client@5.4.2_prisma@5.4.2/node_modules/@prisma/client/runtime/library.js:128:9968)
    at async UserService.deleteUser (/dist/apps/client/main.js:2645:9) {
  code: 'P2003',
  clientVersion: '5.4.2',
  meta: { field_name: 'submission_user_id_fkey (index)' }
}
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/skkuding/next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [X] Check that there isn't already an issue

**Comment by aintbe** [comment]
#961 PR에서 해결한 이슈입니다!
